# Generated by Django 3.2.18 on 2023-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230426_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
                ('imagen', models.URLField(max_length=350)),
            ],
        ),
    ]
